name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - Fiona
  - geopandas
  - geopy
  - networkx
  - scipy
  - seaborn
  - Shapely
  - tqdm
  - libpysal
  - pandarallel
  - haversine
